# Lo más básico

Para trabajar con R es necesario que conozcamos un poco del vocabulario usado en en este lenguaje de programación. Los siguientes son conceptos básicos que usaremos a lo largo de todo el curso.

## La consola de R
Lo primero que nos encontramos al abrir R es una pantalla que nos muestra la versión de este lenguaje que estamos ejecutando y un *prompt*:

`>_                                               ` 

Esta es la consola de R y corresponde con el entorno computacional de este lenguaje. Es aquí donde nuestro código es interpretado.

Podemos escribir código directamente en la consola y R nos dará el resultado de lo pidamos allí mismo. Por esta razón se dice que R permite el uso interactivo, pues no es necesario compilar nuestro código para poder ver sus resultados.

## Ejecutar, llamar, correr y devolver
Cuando hablamos de ejecutar, llamar o correr nos referimos a pedir que R realice algo, en otras palabras, estamos dándole una *entrada*. Por su parte, cuando decimos que R nos devuelve algo, es que ha realizado lo que le hemos pedido, es decir, nos da una *salida*.

## Constantes y variables
Una constante es un objeto cuyo valor no podemos cambiar, en contraste, una variable es un objeto que puede cambiar de valor.

Las constantes y variables en R tienen nombres que nos permiten hacer referencia a ellas.

Las constantes ya están establecidas por R, mientras que nosotros podemos crear variables, asignando valores a un nombre.

Es recomendable que al crear una variable usemos nombres claros, no ambiguos y descriptivos. Esto previene confusión y hace que nuestro código sea más fácil de comprender por otras personas o por nosotros mismos en el futuro.

Los nombres de las variables pueden incluir letras, números, puntos y guiones bajos. Deben empezar siempre con una letra o un punto y si empiezan con un punto, a este no puede seguirle un número.

## Funciones (introducción básica)
Una función es una serie de operaciones a la que le hemos asignados un nombre. Las funciones aceptan argumentos, es decir, especificaciones de cómo deben funcionar.

Cuando llamamos una función, se realizan las operaciones que contiene, usando los argumentos que hemos establecido.

En R reconocemos a una función usando la notación **nombre_de_la_función()**.

Por ejemplo:
- mean()
- quantile()
- summary()
- density()
- c()

Al igual que con las variables, se recomienda que los nombres de las funciones sean claros, no ambiguos y descriptivos. En este caso, que describan lo que hace la función. Es probable que adivines qué hacen casi todas funciones de la lista de arriba a partir de su nombre.

Las funciones son un tema más complejo que esta introducción básica que veremos más adelante. Por el momento, esta descripción basta para entender a qué nos referimos al hablar de una función.
