# Conclusión
Al haber concluido este libro tendrás las herramientas básicas para utilizar R como un lenguaje de programación. Desde los conceptos más básicos, hasta la definición de funciones para exportar gráficos.

Lo que hemos visto en este libro te será de utilidad sin importar el uso de R que tengas previsto, pues son conceptos fundamentales que te permitirán acceder a otros más complejos y avanzado.

El siguiente paso es aplicar lo que hemos revisado hasta este momento, ya sea en algún proyecto propio o para aprender más sobre R y sus aplicaciones.

En caso de que desees profundizar más sobre el uso de R, la siguiente sección te presenta una selección de materiales de referencia que te facilitarán continuar con tu aprendizaje, dependiendo de tus intereses personales.

Todas las referencias incluyen un enlace para que las consultes en línea, sin costo y legalmente.

¡Suerte!

**Material de referencia**

Probabilidad y estadística (introductorio a medio)

*	Diez, D., Barr, C., Çetinkaya-Rundel, M. (2015). *OpenIntro Statistics*, segunda edición. OpenIntro.
  https://www.openintro.org/stat/textbook.php?stat_book=os 
*	Navarro, D. (2015). *Learning statistics with R: A tutorial for psychology students and other beginners*. University of Adelaide.
http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf 


R aplicado a *Data Science* (medio a avanzado)

* Peng, R. D. (2016). *R Programming for Data Science*. Leanpub.  https://leanpub.com/rprogramming  
* Wickham. H. y Grolemund, G. (2017). *R for Data Science*. O’Reilly.   http://r4ds.had.co.nz/


Programación con R (avanzado)

*	Wickham, H. (2014). *Tidy Data*. Journal of Statistical Software. https://www.jstatsoft.org/article/view/v059i10/v59i10.pdf 
*	Wickham, H. (2014). *Advanced R*. O’Reilly. http://adv-r.had.co.nz/ 


Referencias sobre RStudio

*	*RStudio Cheat Sheets*.
  https://www.rstudio.com/resources/cheatsheets/
